In [ ]:
import seaborn as sns
sns.heatmap(df.corr(), annot=True)

In [5]:
import numpy as np
import pandas as pd

arr = np.random.randint(1, 11, size=(3, 4))
print("Original Array:\n", arr)

mean_val = arr.mean()
print("Mean:", mean_val)

reshaped_arr = arr.reshape(2, 6)
print("Reshaped Array:\n", reshaped_arr)

broadcast_result = arr + np.array([10, 20, 30, 40])
print("After Broadcasting:\n", broadcast_result)

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, np.nan, 28, 22],
    'Salary': [50000, 60000, 70000, np.nan, 45000]
}
df = pd.DataFrame(data)
print("\nDataFrame:\n", df)

print("\nSummary Statistics:\n", df.describe(include='all'))

df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].median(), inplace=True)

filtered = df[df['Age'] > 25]
print("\nFiltered (Age > 25):\n", filtered)

df['Department'] = ['HR', 'IT', 'IT', 'HR', 'Finance']

grouped = df.groupby('Department')['Salary'].agg(['mean', 'count'])
print("\nGrouped by Department:\n", grouped)

Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower_bound) | (df['Salary'] > upper_bound)]
print("\nOutliers in Salary:\n", outliers)


Original Array:
 [[10  5  7  8]
 [ 8  6  5  7]
 [ 8  3  7 10]]
Mean: 7.0
Reshaped Array:
 [[10  5  7  8  8  6]
 [ 5  7  8  3  7 10]]
After Broadcasting:
 [[20 25 37 48]
 [18 26 35 47]
 [18 23 37 50]]

DataFrame:
       Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie   NaN  70000.0
3    David  28.0      NaN
4      Eve  22.0  45000.0

Summary Statistics:
          Name    Age        Salary
count       5   4.00      4.000000
unique      5    NaN           NaN
top     Alice    NaN           NaN
freq        1    NaN           NaN
mean      NaN  26.25  56250.000000
std       NaN   3.50  11086.778913
min       NaN  22.00  45000.000000
25%       NaN  24.25  48750.000000
50%       NaN  26.50  55000.000000
75%       NaN  28.50  62500.000000
max       NaN  30.00  70000.000000

Filtered (Age > 25):
       Name    Age   Salary
1      Bob  30.00  60000.0
2  Charlie  26.25  70000.0
3    David  28.00  55000.0

Grouped by Department:
                mean  count
Depart

/tmp/ipykernel_18554/1342038158.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_18554/1342038158.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', 